app.py
import datetime
from flask import Flask, render_template

app = Flask(__name__)

@app.route("/")
def home():
    return render_template('index.html', utc_dt=datetime.datetime.now().astimezone())

@app.route("/about")
def about():
    return render_template('about.html', utc_dt=datetime.datetime.now().astimezone())


@app.route('/comments/')
def comments():
    comments = ['This is the first comment.',
                'This is the second comment.',
                'This is the third comment.',
                'This is the fourth comment.'
                ]

    return render_template('comments.html', comments=comments)

if __name__ == "__main__":
    app.run(host="0.0.0.0", debug=True, port=5001)

app/__init__.py
from flask import Flask
from app.routes import mod_app


app = Flask(__name__)

app.register_blueprint(mod_app)

app/routes.py
from flask import Blueprint, render_template, request
import datetime
import logging
import os

logger = logging.getLogger(__name__)
mod_app = Blueprint('mod_app', __name__,
                    static_folder='static',
                    template_folder=os.path.abspath('templates'))

@mod_app.route("/")
def home():
    return render_template('index.html', utc_dt=datetime.datetime.now().astimezone())

@mod_app.route("/about",  methods=["GET", "POST"])
def about():
    if request.method == "GET":
        return render_template('about.html', utc_dt=datetime.datetime.now().astimezone())
    else:
        print(request.form)

@mod_app.route('/comments/')
def comments():
    comments = ['This is the first comment.',
                'This is the second comment.',
                'This is the third comment.',
                'This is the fourth comment.'
                ]

    return render_template('comments.html', comments=comments)

templates/about.html
{% extends 'base.html' %}
{% block title %}
About Page
{% endblock %}
{% block custom_js %}
<script src={{ url_for('mod_app.static',filename='js/hello.js' ) }}></script>
{% endblock %}
{% block content %}
<h1>About Page - With Base Template File</h1>
<h2>Welcome to FlaskApp!</h2>
<h3>{{ utc_dt }}</h3>

{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

    <title>{% block title %} {% endblock %} - FlaskApp</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="{{ url_for('mod_app.home') }}">FlaskApp</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('mod_app.comments') }}">Comments</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('mod_app.about') }}">About</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container">
        {% block content %} {% endblock %}
    </div>
    {% block custom_js %}{% endblock %}
    <!-- Optional JavaScript -->

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj"
        crossorigin="anonymous"></script>

</body>

</html>

templates/comments.html
{% extends 'base.html' %}

{% block content %}
<h1>{% block title %} Comments {% endblock %}</h1>
<div style="width: 50%; margin: auto">
    {% for comment in comments %}
    {% if loop.index % 2 == 0 %}
    {% set bg_color = '#e6f9ff' %}
    {% else %}
    {% set bg_color = '#eee' %}
    {% endif %}
    <div style="padding: 10px; background-color: {{ bg_color }}; margin: 20px">
        <p>#{{ loop.index }}</p>
        <p style="font-size: 24px">{{ comment | upper }}</p>
    </div>

    {% endfor %}
    <hr>
    <div>
        <p>{{ comments | join(" | ") }}</p>
    </div>
    <hr>
    <div>
        {{ "<h1>COMMENTS</h1>" | safe }}
        <p>{{ comments | join("
            <hr> ") | safe }}
        </p>
    </div>
</div>
{% endblock %}

templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>FlaskApp</title>
</head>

<body>
    <h1>Hello World!</h1>
    <h2>Welcome to FlaskApp!</h2>
    <h3>{{ utc_dt }}</h3>
    <!-- <script src="./hello.js"></script> -->
</body>

</html>